// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3qWMj8yAWQVAYKuNmn5Sc3QBy3rdC_k',
    appId: '1:897182599759:android:3044f9dc0c446b7281f83a',
    messagingSenderId: '897182599759',
    projectId: 'testnewtyapp',
    storageBucket: 'testnewtyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8eANkXNEHBZKVy65Q39qVUt2eyaADuY8',
    appId: '1:897182599759:ios:2e42a02bf253570681f83a',
    messagingSenderId: '897182599759',
    projectId: 'testnewtyapp',
    storageBucket: 'testnewtyapp.firebasestorage.app',
    androidClientId: '897182599759-g60juut3ehrtpn5n86f1gvffa1pi661q.apps.googleusercontent.com',
    iosClientId: '897182599759-rht78nk8lctlgo6c8sbiia516si4g3bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.educappDemo',
  );
}
